<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Cache.Core</AssemblyName>
    <RootNamespace>DioRed.Cache.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cache.Domain\Cache.Domain.csproj" />
  </ItemGroup>

</Project>
