<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DioLive.Cache.Common\DioLive.Cache.Common.csproj" />
    <ProjectReference Include="..\DioLive.Cache.Storage\DioLive.Cache.Storage.csproj" />
  </ItemGroup>

</Project>