<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Cache.Domain</AssemblyName>
    <RootNamespace>DioRed.Cache.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DioRed.Common.Results" Version="1.2.3" />
  </ItemGroup>

</Project>
